IP 스푸핑 방지 및 ruby 문법 지원
gdl-888/imitated-seed-v2 pull request #293
Opened 2024-12-22 04:31 UTC by theseeduse

# 서론

누가 그랬는지 별도로 명시하지는 않겠으나 [어떤 정신나간 위키 소유자](https://github.com/NOAH01112)가 본 코드와 관련된 계약을 위반하여 계약에 따라 오픈소스로 전환된 사항입니다.

# 추가 사항

추가된 사항은 다음과 같습니다.

 - IP 스푸핑 방지(CloudFlare 연계) 
 - Ruby 문법 지원(ex: [ruby(라이선스, ruby=위반 작작해라, color=red)])

# 주의 사항
 - IP 스푸핑 방지를 원하시면 config.json에서
 ```json
 {"use_cloudflare":"true"}
``` 로 바꾸신 뒤, **cloudflare 프록시 설정을 on으로 바꿔주세요.**
 - ruby 문법은 the seed와 사실상 동일하게 작동합니다.
 - 본 PR에 적용된 코드는 all right reserved입니다.

2024-12-22 07:07 UTC, navyCarpet commented
테스트는 해보셨나요??

2024-12-22 07:29 UTC, theseeduse commented
> 테스트는 해보셨나요??

네 현재 본인 위키에 구동하는 파일 그대로입니다

2024-12-22 07:35 UTC, theseeduse commented
일단 혹시 모르니 다시 한번 해보겠습니다

2024-12-22 07:50 UTC, theseeduse commented
까먹고 디버깅한 부분 안 올려뒀습니다. 다시 올렸습니다.

2024-12-22 07:52 UTC, theseeduse commented
추가로 만약 본 PR 적용하고 use_cloudflare 값을 true로 둬도 스푸핑이 가능하다면 다음 코드를 직접 추가하셔도 스푸핑 방지가 가능합니다.(config.json)
```json
{"custom_ip_header":"CF_Connecting_IP"}
```

2024-12-22 09:33 UTC, navyCarpet requested changes
프라이빗 테스트 위키에서 해당 렌더러 파일을 넣고 테스트해 보았는데,
1. ruby function call이 html.escape 위에 있어 ruby가 적용될 수 없음
2. 리터럴보다 위에 있기에 리터럴이 될 수 없음
3. chatgpt가 만든 코드처럼 보이는데 저작권을 주장하시는 건...

2024-12-22 10:22 UTC, theseeduse commented
> 프라이빗 테스트 위키에서 해당 렌더러 파일을 넣고 테스트해 보았는데,
> 
> 1. ruby function call이 html.escape 위에 있어 ruby가 적용될 수 없음
> 2. 리터럴보다 위에 있기에 리터럴이 될 수 없음
> 3. chatgpt가 만든 코드처럼 보이는데 저작권을 주장하시는 건...

1. 잘못 적용하였습니다 패치했습니다
2. 실 사용시 큰 문제는 없으나 우선 패치했습니다
3. color 구문 추가할 때에만 일부 사용하였습니다. [the seed 렌더링](https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EC%97%B0%EC%8A%B5%EC%9E%A5?uuid=cd06374c-feb4-4bfb-97d7-80f120fa3988) 보시면 대문자 렌더링은 되지 않아 해당 부분은 삭제하였습니다. 또한 [이상한 사람들](https://github.com/NOAH01112)이 본인 코드니 어쩌니 하면서 떠들어대는 경우가 있어서 명시해뒀습니다.

2024-12-22 10:25 UTC, navyCarpet commented
function 정의를 아래로 내린다고 리터럴이 적용되는 것이 아닙니다.
`data = ruby(data);`를 1024줄까지 내려보십쇼

2024-12-22 10:26 UTC, navyCarpet commented
개발자가 비슷한 문법끼리 가까운 곳에 묶어 놓았는데 참고해서 가까운 곳에 놓으시면 좋을 것 같습니다

2024-12-22 10:30 UTC, navyCarpet commented on namumark_parser.js
> +        	const rubyPattern = /\[ruby\(([^,]+),\s*ruby=([^,\)]+)(?:,\s*color=?\{?([^\}\)]+)\}?)?\)\]/g;
그런데 color에 중괄호는 왜 필요한 것인가요?

2024-12-22 23:45 UTC, theseeduse commented on namumark_parser.js
> +        	const rubyPattern = /\[ruby\(([^,]+),\s*ruby=([^,\)]+)(?:,\s*color=?\{?([^\}\)]+)\}?)?\)\]/g;
> 그런데 color에 중괄호는 왜 필요한 것인가요?

어 저거 왜 들어가있지 잘못 넣은건데 바로 수정하겠습니다

2025-08-12 08:40 UTC, closed without merging

2026-01-01 13:20 UTC, gdl-blue commented
근데 'trust proxy'를 true로 하지 않는 이상 x-forwarded-for는 무시되는 걸로 압니다